### ISSUE TITLE
installing gsea-desktop

### ISSUE THREAD

**Issue by Paolo7X86** [GSEA-MSigDB/gsea-desktop#1]
Hello there. I can't install the software. I can download the archive and open it. But I can't open any of the files present, apart from a couple of text files. Briefly, I can't run the installation process.
Know that Java 8 is installed in my computer. I am using a PC.
Can you help me with the present issue, please?
Best.
Paolo

**Comment by davideby** [comment]
Hi Paolo,

The best place to get the application is from the [Download page](http://www.gsea-msigdb.org/gsea/downloads.jsp) of the GSEA website.  From there, you can either Launch with Java directly (JNLP) or download a runnable JAR file.  Either of those should work fine since you have Java installed.  You can just double-click on the downloaded JAR to launch; check the [User Guide for other ways to launch](http://software.broadinstitute.org/gsea/doc/GSEAUserGuideFrame.html?_Running_GSEA_from_the%20Command%20Line).  The Launch with Java option should be the simplest.

We don't distribute ZIPs of the application, so if you've downloaded that from elsewhere you should probably discard it and go to the website.  If you are downloading a ZIP from GitHub, that's mostly useful to a Java developer looking to work on GSEA code rather than a user who wants to run analyses.

The best place for user support is the [GSEA forum](https://groups.google.com/group/gsea-help) linked from there.  The GitHub forum is better for code-related questions.  We'll try to answer from here as well, but the forum there is better for users.

Regards,
David
