### ISSUE TITLE
Problem to run GSEA with pre-ranked gene list

### ISSUE THREAD

**Issue by Pallavimore** [GSEA-MSigDB/gsea-desktop#23]
I am doing pathway enrichment analysis of a ranked gene list using the GSEA pipeline. I have created my pre-ranked file using EdgeR gene expression data. Following is the example of my ranked gene list file.

```
GeneName	rank
Nradd	47.5158752842802
Lamb1	46.40008428503
Smpdl3b	43.3594100528077
Nsg1	42.6613014732087
Pcolce2	39.1122051313585
Tubb2b	38.1728810609628
Ccn3	34.6352256979414
Rassf9	32.7306194473928
```
When I load input data in GSEA, the next step is Run Gsea on pre-ranked gene list. I am getting the following error.

![GSEA_error](https://user-images.githubusercontent.com/56917248/68849386-f7a9a380-06f7-11ea-8170-5278cf843f97.png)

If I used a pre-ranked file from provided supplementary files then it is running fine. I am not able to understand what could be the problem with my pre-ranked file. Once I run gene set enrichment analysis then I need to load GSEA results in EnrichmentMap in cytoscape for visualization.

Could anyone please help me to resolve the issue.

Thank you.

**Comment by ACastanza** [comment]
Hi,

Generally, we ask that these sorts of questions be directed to the GSEA-help forum (https://groups.google.com/forum/#!forum/gsea-help), where you might find that it has already been answered and/or others might be able to benefit from a new answer in turn.

That said, it appears as if you are using Mouse or Rat gene symbols in your ranked list. If you are running this data against gene sets acquired from the Molecular Signatures Database (MSigDB) (the gene sets present in GSEA's "Gene matrix from website" dialogue) you will need to use one of the provided "Gene_Symbol_Remapping" chip files (such as Mouse_Gene_Symbol_Remapping_MSigDB.v7.0.chip) in order to perform an orthology conversion as MSigDB represents gene sets using Human Gene Symbols.

In order to apply this chip to a preranked file you'll need to set a Collapse/Remap to Gene Symbols mode, normally we recommend that this be set to Remap_Only, but for orthology conversion, you'll want to set this to "Collapse" which will use the largest magnitude value in the cases of multimapped orthologues.

If this doesn't resolve your error there are other solutions we can consider. If it does, please let me know so I can close this issue.

-Anthony

Anthony S. Castanza, PhD
Curator, Molecular Signatures Database
Mesirov Lab, Department of Medicine
University of California, San Diego

**Comment by Pallavimore** [comment]
Hi Anthony,

Thank you so much for your response. Yes, it worked for me.
