### ISSUE TITLE
Timestamp Parameter Value Exposure 

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/gsea-desktop#28]
GSEA results are associated with two different timestamps. The Timestamp used as the random seed which is output under the "Comments" section on the results index page, and a second timestamp "producer_timestamp" which is output on the "Parameters used for this analysis" page. This later timestamp is also used to name the GSEA output directory for the run.

The problem is that the important timestamp, the Random Seed, is only displayed on the Index page not the parameters page. At minimum this stamp should be printed on the parameters page where it can be made clear that this timestamp, not the producer timestamp is the essential value for reproducing a GSEA result.

Ideally, when timestamp seed is used that timestamp should also be what is used to name the GSEA output directory, but that is probably harder to implement and would result in a small inconsistency when a non-timestamp seed was used.

**Comment by davideby** [comment]
Yes, good suggestions.  As we discussed separately, the code around this is convoluted but we should at least be able to tack on a field at the end of the parameters file even if it doesn't get used by the analysis (e.g. actual_timestamp or random_seed_timestamp).

We should consider this for a 4.1.x update.

There's a slight complication in that the current behavior of reloading & re-running such an analysis is to use a new timestamp random seed each time.  However it's arguably beneficial to be able to instead re-use the random_seed_timestamp in such cases in order to exactly reproduce the result.  

Your suggestion of an extra Advanced parameter plus an override preference to control this behavior might be worthwhile.

On a separate but related topic, we should consider revamping path naming in the directory hierarchy, which might get rid of the need for the producer_timestamp.  Its similarity of name/purpose is somewhat confusing so it would be nice if we could drop it (see #29)

**Comment by davideby** [comment]
Fixed in the 4.2.x releases.
