### ISSUE TITLE
GCT and CLS files not saved in Recently Used Files

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/gsea-desktop#30]
It appears that GCT and CLS files are not being saved in the "recently used files" list.
They appear there after being loaded through Method 3, but don't persist after application restart.

Txt files and Rnk file appear, but the most used file types for default GSEA seems to be erroneously forgotten.

**Comment by davideby** [comment]
@ACastanza Interesting bug here, or more like particular circumstances...

There's a hard-coded limit of 30 files loaded in the Recent Files list (refreshed from file on start-up).  If you have more than that in the list (saved on the previous exit), then it cuts off any at the *top* of the list, regardless of type.  But it just so happens that the list is sorted to have the *most popular types* (GCT and CLS) *at the top*.

So, if you purge the list and then load a GCT and CLS they'll stick around, but if the list is full then they'll always be removed.  We could specifically remove other types, but whatever we do in that case would be arbitrary.

The nicest fix would be to drop the Least Recently Used.  That's probably what most users would expect (by the term "Recently").  We don't track time of use, though, so that would be difficult.

**Comment by ACastanza** [comment]
Do we track when the files were initially loaded? Removing the oldest mind
be good enough, it's fairly unlikely that the oldest files would also be
the most recently used while simultaneously also hitting the list limit
(which we should probably also increase slightly).

Even if that did happen it's still a better solution than just chopping off
the top of the list...

**Comment by davideby** [comment]
No, there's no associated date/time at all.  In fact, the whole thing is a bit clunky: the only reason CLS and GCT are at the top is because of alphabetical ordering, not because they are commonly used.

Adding a timestamp into this code is difficult.  I'm working on a different idea, though, which is to just keep the relative order of the loading intact but only sort the files (by extension) _for presentation purposes_ in that list.  Then we can just always drop things off the end of the list (*not* the top).

Although, another way to go is to present that list in order of use, which is the way most applications do it (e.g. Word, Excel).  We're the ones deviating from normal UI standards here.  It's a pretty big change from old behavior, though, and would lead to that list being resorted on they fly right in front of the user.

**Comment by davideby** [comment]
This was fixed a while ago.
