### ISSUE TITLE
GSEA for zebrafish

### ISSUE THREAD

**Issue by demis001** [GSEA-MSigDB/gsea-desktop#31]
I have no issue when I use gsea with human and mouse. BUT, I am quite confused which underlying Gene Set should I use for zebrafish?  How can I create *.gmt file for other organism? The result is not good when I use C2.all.v7.1symbol.gmt for zebrafish.  I have a preranked rnaseq data with zebrafish genesymbol. 

 I remember, when did the same thing  with mouse ranked data, I got a weird result a while ago, BUT, after I provided "Mouse_AllPathways_March_01_2017_symbol_gmt" downloaded form other source and loaded the gsea gave the right result. Any idea how should I generate gmt for zebrafish? Is it ok to use C2.all.v7.1.symbol.gmt with zebrafish pre-ranked data?

**Comment by demis001** [comment]
HI Anthony,

Thank you very much!  Would you please elaborate how to create the CHIP
file in biomaRt. I used BiomaRt extensively to download annotations.

Best,
Dereje

**Comment by ACastanza** [comment]
This isn't a procedure that we officially support, so I can't really give you an official recommendation. That said, we did use an Ensembl Biomart based procedure for orthology mappings in MSigDB 7.0 before we switched to the MGI process in MSigDB 7.1.
We Describe that process in brief here: https://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/MSigDB_v7.0_Release_Notes#Change_to_gene_orthology_mapping_procedure_for_non-human_gene_sets
In order to get Human Symbols that match the current version of MSigDB (7.1) you'll need to use this ensembl archive: http://jan2020.archive.ensembl.org/index.html
