### ISSUE TITLE
Size thresholds

### ISSUE THREAD

**Issue by Lila14** [GSEA-MSigDB/gsea-desktop#5]
I ran GSEA with default parameters (no Chip platform). I've attached my files. Some of the gene sets do have at least 15 elements, so not sure what's going on.

> INFO - Got gsets: 34 now preprocessing them ... min: 15 max: 500
> INFO - Done preproc for smaller than: 15
> ERROR - Tool exec error
> xtools.api.param.BadParamException: After pruning, none of the gene sets passed size thresholds.
> 	at xtools.api.param.ParamFactory.checkAndBarfIfZeroSets(ParamFactory.java:88)
> 	at xtools.gsea.Gsea.execute(Gsea.java:111)
> 	at edu.mit.broad.xbench.tui.TaskManager$ToolRunnable.run(TaskManager.java:436)
> 	at java.lang.Thread.run(Thread.java:748)

[EB1_iPSC-GFP-TAM_KO_annotation.cls.txt](https://github.com/GSEA-MSigDB/gsea-desktop/files/2036142/EB1_iPSC-GFP-TAM_KO_annotation.cls.txt)
[GENE_LIST_RNAseq_exampleIE.gmt.txt](https://github.com/GSEA-MSigDB/gsea-desktop/files/2036145/GENE_LIST_RNAseq_exampleIE.gmt.txt)
[EB1_iPSC-GFP-TAM_KO_counts.gct.txt](https://github.com/GSEA-MSigDB/gsea-desktop/files/2036150/EB1_iPSC-GFP-TAM_KO_counts.gct.txt)

**Comment by davideby** [comment]
Hi,

It's very likely caused by a mismatch between the gene symbols in the expression data set and the gene symbols in the files.  Have a look at [this thread](https://groups.google.com/d/msg/gsea-help/VOdFCAICi2Q/KJWVw2zXCAAJ) on our Help Forum for a more detailed explanation.

Also, just fyi the GSEA Desktop uses the file extension to decide how to process the file, so having extensions like ".cls.txt" and the others may confuse it.  It's better to have simply ".cls", ".gmt", and ".gct" instead.

Regards,
David
